### ISSUE TITLE
New plugin parameter: description

### ISSUE THREAD

**Issue by daviedR** [TGMPA/TGM-Plugin-Activation#533] opened 2016-02-09 13:49 UTC
Hi guys,

I would suggest a new parameter for the plugins, the `description` parameter. It would help authors to describe how the required plugins are important to install. On the other hand, users might need to know how the required plugins will help their site before they decide to use the plugin.

The description text should be displayed on the TGMPA page (a new column)

e.g.
Kirki Toolkit: This plugin is mandatory and must be installed, otherwise all the Customizer options might be disappeared.
Contact Form 7: This plugin will help you to create contact form and embed the form in your pages.
Attachments: Installing this plugin will enable the "Page Attachments" options on your page editor.

What do you think?

Regards

**Comment by jrfnl** [comment] 2016-02-09 18:35
Closing as duplicate of #259.

**Closed** 2016-02-09 18:35 UTC
Labels: duplicate
