### ISSUE TITLE
Are you sure you want to do this?

### ISSUE THREAD

**Issue by chrisSowerby** [TGMPA/TGM-Plugin-Activation#497] opened 2015-12-14 09:48 UTC
* @version    2.5.2

Hi I get "Are you sure you want to do this?"  when i try to load a dashboard page.

I have found that it is because of this:

        //https://wordpress.org/plugins/no-captcha-recaptcha/
        array(
            'name'      => 'No CAPTCHA reCAPTCHA',
            'slug'      => 'no-captcha-recaptcha',
            'required'  => true,
            'force_activation'   => true, // If true, plugin is activated upon theme activation and cannot be deactivated until theme switch.
        ),

As soon as i remove the above from my plugins array it fixes the issue and stops putting out the "Are you sure you want to do this?" message.

Not sure what it is about this bit of code that causes this?

cheers.

**Comment by jrfnl** [comment] 2016-01-04 13:07
Hi @chrisSowerby,

I've had a look at this and can reproduce the issue easily.

The problem is not so much in the code in your plugins array, but in the actual "No CAPTCHA reCAPTCHA" plugin itself. It does a hard check whether activation is done from the plugins page and if not, throws a `wp_die()`.

As with `force_activation => true`, TGMPA will keep trying to activate the plugin, every admin page load will result in the `Are your sure ?` message.

I've send in a PR to the plugin owner to fix this: https://github.com/collizo4sky/No-CAPTCHA-reCAPTCHA/pull/9

**Comment by jrfnl** [comment] 2016-03-28 20:09
Closing as the fix for this has been merged in the No Captcha Recaptcha plugin.

**Closed by jrfnl** 2016-03-28 20:09 UTC
