### ISSUE TITLE
Avoid automatic updates, Visual Composer

### ISSUE THREAD

**Issue by lidplussdesign** [TGMPA/TGM-Plugin-Activation#437] opened 2015-06-27 10:26 UTC
How to avoid automatic updates license activation, here is the problem we have with Visual Composer plugin now http://lpd-themes.d.pr/1kApp when we try to update it.

Thank you

**Comment by jrfnl** [comment] 2015-06-27 10:49
Closing as a duplicate of #407

**Closed by jrfnl** 2015-06-27 10:49 UTC
Labels: duplicate
