### ISSUE TITLE
Escape _n_noop()

### ISSUE THREAD

**Issue by cristianstan** [TGMPA/TGM-Plugin-Activation#559] opened 2016-04-08 13:45 UTC
I just got rejected on ThemeForest because of non escaped data in TGMPA. 

So to escape this type of strings:
`			'oops'                            => __( 'Something went wrong with the plugin API.', 'tgmpa' ),`
This will become:
`			'oops'                            => esc_attr__( 'Something went wrong with the plugin API.', 'tgmpa' ),`

But how do I escape the singular/plural strings?
```
				'notice_can_activate_required'    => _n_noop(
					'The following required plugin is currently inactive: %1$s.',
					'The following required plugins are currently inactive: %1$s.',
					'tgmpa'
				),
```
Thank you

**Comment by jrfnl** [comment] 2016-04-08 14:07
Strings should be escaped *late*, i.e. at the point at which they are being used, not before. TGMPA does just that.
Closing as duplicate of #541.

I suggest Themeforest reviews how they test for escaped strings as TGMPA complies with all relevant best practices for escaping strings. /cc @Stephen-Cronin

**Closed by jrfnl** 2016-04-08 14:07 UTC
Labels: duplicate, invalid

**Comment by Stephen-Cronin** [comment] 2016-04-11 06:14
Hey @cristianstan 

I just checked under your christianstan account on TF and can't find it, but if you let me know which theme it was, I'll look into the issue. Probably best for you to [submit a ticket](https://help.market.envato.com/hc/en-us/requests/new) rather than us discussing it here (as it's not a TGMPA issue). Make sure to ask for me in the ticket so it gets to me quicker. Thanks.

Stephen

**Comment by Mcurly17** [comment] 2016-07-24 19:59
Hello,

Did you find a solution ? I'm stuck with exactly the same problem. I don't know what to do.

Is there a way to escape n_noop function ? Thanks.

**Comment by jrfnl** [comment] 2016-07-24 20:04
@Mcurly17 Please follow @Stephen-Cronin's advise to open a ticket at TF. This is not a TGMPA issue.

**Comment by Mcurly17** [comment] 2016-07-24 20:19
@jrfnl ok thanks, I'll see with him.
