### ISSUE TITLE
How to: check from theme if all the required plugins installed?

### ISSUE THREAD

**Issue by pavot** [TGMPA/TGM-Plugin-Activation#485] opened 2015-10-06 22:20 UTC
Hi @GaryJones and @jrfnl,
first of all thank you for amazing work done on this plugin!

I'm wondering if there is any way from the theme functions.php to call **is_tgmpa_complete()**? We have a theme installer and the first step of this installer is "Install required plugins" like on [the screenshot](https://www.evernote.com/l/AAEu_h_StrBNO63SWyghi2nOB4QgN_Eexl0). Not sure if there is any way to call **is_tgmpa_complete()** outside the class code to mark this step as DONE.

Thanks for your time and advice!

**Comment by jrfnl** [comment] 2015-10-07 12:33
Closing as duplicate of #484.

You can use `TGM_Plugin_Activation::get_instance()->is_tgmpa_complete()`, but as this method is meant for internal use, it *will* report `false` if there are plugins which need updates.

Hope this helps.

**Closed by jrfnl** 2015-10-07 12:33 UTC
