### ISSUE TITLE
Non-Dismissible only for required plugins

### ISSUE THREAD

**Issue by AlexandruDoda** [TGMPA/TGM-Plugin-Activation#411] opened 2015-05-17 09:36 UTC
Is there any way to make the admin notice non-dismissible only if it contains stuff related to required plugins? I would like to allow the user to dismiss if the required plugins are installed and there are only recommended ones left. Currently, I can only make it dismissible or non-dismissable overall.

**Comment by jrfnl** [comment] 2015-05-20 08:38
Closing as duplicate of #248

**Closed by jrfnl** 2015-05-20 08:38 UTC
Labels: duplicate
