### ISSUE TITLE
Using as plugin: Conflict with themes

### ISSUE THREAD

**Issue by nilsbyte** [TGMPA/TGM-Plugin-Activation#572] opened 2016-04-29 13:18 UTC
I am using this as a plugin to install often used plugins with ease. Unfortunately many themes use TGM and cause some kind of conflict with my plugin. Either the contents of the theme-based TGM and my plugin are merged or i get a HTTP 500 after activating my plugin.

 Is it possible to adjust everything so that it would not collide with already present TGM instances?

**Comment by jrfnl** [comment] 2016-04-29 21:46
@nilsbyte Please provide us with more detail.
In principle those issues have all been solved in recent TGMPA versions, however, we have no power to force themes/plugins to upgrade the version they include and some may still include the (very) old buggier versions.

As plugins are loaded before themes, if you make sure your plugin includes the latest version of TGMPA, this should solves things 98% of the times. For the other 2%, contact the theme developer to upgrade the version of TGMPA they include and - until they do - replace the version included in the theme in your install with the current version of TGMPA.

As for the theme and plugin TGMPA page being 'merged' - that's by design.

Hope that answers your question.

**Comment by jrfnl** [comment] 2016-06-05 18:32
@nilsbyte Just checking: can we close this issue ? If not, please let us know how we can help.

**Comment by GaryJones** [comment] 2016-10-01 10:48
Closing for lack of response.

**Closed by GaryJones** 2016-10-01 10:48 UTC
Labels: Status: Reporter Feedback Needed
