### ISSUE TITLE
Return to the dashboard custom link 

### ISSUE THREAD

**Issue by AlexandruDoda** [TGMPA/TGM-Plugin-Activation#553] opened 2016-03-30 23:15 UTC
It would be very useful if we could control where the user goes after all plugins are installed. Maybe a parameter that lets us select which page from the admin area the "Return to the dashboard" would go to.

**Comment by jrfnl** [comment] 2016-03-31 02:48
Closing as duplicate of #434

**Closed by jrfnl** 2016-03-31 02:48 UTC
Labels: duplicate
