### ISSUE TITLE
If a plugin has your file in the root of their folder, it can screw up author attribution in the wordpress.org plugin repo

### ISSUE THREAD

**Issue by Ipstenu** [TGMPA/TGM-Plugin-Activation#558] opened 2016-04-05 20:02 UTC
https://cloudup.com/c2q01t6dZf5

Basically this is because of https://plugins.svn.wordpress.org/better-coupon-box/trunk/class-tgm-plugin-activation.php

By having it in root, it's doing this as you're using WordPress' plugin headers and WP is detecting that.

**Comment by jrfnl** [comment] 2016-04-05 21:00
Hi Mika, thanks for reporting this.
Closing as duplicate of #499 which was fixed with PR #500. The fix will be included in TGMPA v 2.6.0 which we expect to release within the next few weeks.

**Closed by jrfnl** 2016-04-05 21:00 UTC
Labels: duplicate
